### ISSUE TITLE
How to initialize hyperparameter space after changing configurations?

### ISSUE THREAD

**Issue by deng-cy** [automl/Auto-PyTorch#32]
After changing configurations, e.g., setting preprocessors=['power_transformer'] from the tiny_cs config, I got an error saying "Invalid search space update given: truncated_svd:target_dim". It seems I need to re-initialize the hyperparameter space. How to do that?

**Comment by LMZimmer** [comment]
The issue is that when initializing with "tiny_cs" the configspace object only contains very few options. What you can do is initializing with "full_cs" and then updating the ranges to remove any options you do not want in there as shown on the [main page](https://github.com/automl/Auto-PyTorch#configuration).
