### ISSUE TITLE
Release 0.0.2 two years old

### ISSUE THREAD

**Issue by l0rs123** [automl/Auto-PyTorch#333]
Currently me and my colleagues are working on a project called Meta AutoML (https://projects.fbi.h-da.de/~b.humm/pub/Humm%20Zender%20-%20Ontology_based_Meta_AutoML.pdf). 
For this project we wanted to use your Library too, but as your last release is two years old and you have a complete new structure on your development-branch I am curious about your next stable release. 
When will it be and what's your concept for your upcoming releases?

**Comment by ravinkohli** [comment]
Thanks for your question. We are in the last phase of making the release for the development branch. It should be out very soon (by the end of November, hopefully). Can I ask what exactly you mean by the concept of upcoming releases?

**Comment by l0rs123** [comment]
Thank you for your answer. It's good to hear about your release date! 
With "concept for your upcoming releases" I mean: 
- Have you a kind of schedule to release regularly?
- Is it expectable that you try to not break the compatibility from this version to a newer version? (Asking because of the incompatibility between development-branch to release-v0.0.2)

**Comment by ravinkohli** [comment]
We are working on a schedule to release regularly now. The reason for a huge incompatibility between release 0.0.2 and the new release `0.1.0` was that it was hard to maintain 0.0.2 in its current form as well as some much needed upgrade on vital components like the use of `SMAC` instead of `BOHB` from [`hpbandster`](https://github.com/automl/HpBandSter). So to make it more maintainable and align it with the group's other repositories. 

We do not see the need to make compatibility breaking changes anytime soon.

**Comment by l0rs123** [comment]
Thanks for these clear statements!
