### ISSUE TITLE
Multi-label classification error?

### ISSUE THREAD

**Issue by redreamality** [automl/Auto-PyTorch#392]
NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://stackoverflow.com

Your issue may already be reported!
Also, please search on the [issue tracker](../) before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

# Issue Description
* When Issue Happens
* Steps To Reproduce

```python
import sklearn.model_selection
from sklearn.datasets import make_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils import shuffle
import numpy as np
from autoPyTorch.api.tabular_classification import TabularClassificationTask


X, y1 = make_classification(n_samples=10, n_features=100, n_informative=30, n_classes=1, random_state=1)
y2 = shuffle(y1, random_state=1)
y3 = shuffle(y1, random_state=2)
Y = np.vstack((y1, y2, y3)).T
n_samples, n_features = X.shape # 10,100
# n_outputs = Y.shape[1] # 3
# n_classes = 3
# forest = RandomForestClassifier(random_state=1)
# multi_target_forest = MultiOutputClassifier(forest, n_jobs=-1)
# multi_target_forest.fit(X, Y).predict(X)

X_train, X_test, y_train, y_test = \
        sklearn.model_selection.train_test_split(X, Y, random_state=1)

# initialise Auto-PyTorch api
api = TabularClassificationTask()

# Search for an ensemble of machine learning algorithms

api.search(
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    optimize_metric='accuracy',
    total_walltime_limit=300,
    func_eval_time_limit_secs=50
)

# Calculate test accuracy
y_pred = api.predict(X_test)
score = api.score(y_pred, y_test)
print("Accuracy score", score)
```

## Error message

```
...../site-packages/autoPyTorch/datasets/tabular_dataset.py in __init__(self, X, Y, X_test, Y_test, resampling_strategy, resampling_strategy_args, shuffle, seed, train_transforms, val_transforms, dataset_name, validator)
     88                          val_transforms=val_transforms)
     89         if self.output_type is not None:
---> 90             if STRING_TO_OUTPUT_TYPES[self.output_type] in CLASSIFICATION_OUTPUTS:
     91                 self.task_type = TASK_TYPES_TO_STRING[TABULAR_CLASSIFICATION]
     92             elif STRING_TO_OUTPUT_TYPES[self.output_type] in REGRESSION_OUTPUTS:

KeyError: 'multilabel-indicator'

```

## Your Local environment
* Operating System, version
* Python, version
* Outputs of `pip freeze` or `conda list`

Make sure to add **all the information needed to understand the bug** so that someone can help. 
If the info is missing, we'll add the 'Needs more information' label and close the issue until there is enough information.

**Comment by ravinkohli** [comment]
I think there is a logical error in your code, you have passed `n_classes=1`. And hence your `y` only contains zeros. Moreover, you get this error because we don't support `multilabel-indicator` task yet. Therefore, I am closing this issue. If you get any other errors please feel free to open a new issue.

**Comment by MBrede** [comment]
Hi all, hi @ravinkohli,
I hope it is alright to not open a new issue but to ask here:
I am running into the same error and was wondering if it is a mistake on my end or just to missing support for multilabel-tasks. Since it is not mentioned in your constants.py, am I right to assume that you did not get around to adding this functionality until now?
If it is so, I would switch to multiclass, though I am not too happy about this option.
Thank you for your great work!
