### ISSUE TITLE
where to find the available include_components list?

### ISSUE THREAD

**Issue by fun1997** [automl/Auto-PyTorch#478]
and how to define my own  activtion function for neural network ?
Very thanks for anyone can help

**Comment by theodorju** [comment]
Hi @fun1997, since at this point there is no list for all available options of `include_components` you'll have to do a bit of searching through the source code for the component you would like to specify. You can find one example of what the `include_components` should look like [here](https://automl.github.io/Auto-PyTorch/development/examples/40_advanced/example_custom_configuration_space.html#build-and-fit-a-classifier-with-include-components).

Currently, custom activation functions are not supported so I would suggest modifying the dictionary in [this](https://github.com/automl/Auto-PyTorch/blob/56a2ac1d69c7c61a847c678879a67f5d3672b3e8/autoPyTorch/pipeline/components/setup/network_backbone/utils.py#L12) file with your own activation key-value pair as a workaround.

**Comment by theodorju** [comment]
I've opened an issue to possibly improve the documentation regarding this functionality.

I am closing this issue. @fun1997, feel free to re-open if any issue appears.
